name: Nifty Scanner Every 10 Min

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (in UTC)
  workflow_dispatch:       # allows manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests

      - name: Run pattern scanner
        run: python scanner.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
